### ISSUE TITLE
Generation of files mtx

### ISSUE THREAD

**Issue by AndyLiuin** [tRowans/radial-codes-public#1]
Hi,

I'm trying to run your code and I see there is the file format mtx for QDistRnd. I'm wondering if there is a file generating mtx from, say, numpy array of parity-check matrices. Or otherwise how did you do it?

Thanks.

**Comment by tRowans** [comment]
Hi,

There is a function (`write_PCM_as_mtx`) at line 77 of generation/codegen.py that does this. It takes some extra arguments as well but this is just for writing some extra information about the codes in the mtx header and isn't needed for QDistRnd. You could edit it to get a minimal version that just takes `H` and `pauli` which should do exactly what you ask.

**Comment by AndyLiuin** [comment]
Thanks!!!

**Comment by esabo** [comment]
Note that QDistRnd (in GAP) is extremely slow. We've rewritten an optimized version of it from scratch which is multithreaded in Julia. Hope to have it polished for general use by the end of the month, but if you have some test cases you'd care to run we can set that up.

**Comment by AndyLiuin** [comment]
> Note that QDistRnd (in GAP) is extremely slow. We've rewritten an optimized version of it from scratch which is multithreaded in Julia. Hope to have it polished for general use by the end of the month, but if you have some test cases you'd care to run we can set that up.

Thanks! Sure I'll be interested, what would be the best way of contact?
